PROJECTS:
      '00': "All_projects"
      '01': "LogisticRegression model"
      '02': "Project Excecuter DataLoad"
      '03': "XGBoost model"
FEATURES:
      'timestamp': True  
      'project_name': True
      'run_id': False
      'duration': True
      'emissions': True
      'emissions_rate': True
      'cpu_power': False
      'gpu_power': False
      'ram_power': False
      'cpu_energy': False
      'gpu_energy': False
      'ram_energy': False
      'energy_consumed': True
      'country_name': False
      'country_iso_code': False
      'region': False
      'cloud_provider': False
      'cloud_region': False
      'os': False
      'python_version': False
      'codecarbon_version': False
      'cpu_count': False
      'cpu_model': False
      'gpu_count': False
      'gpu_model': False
      'longitude': False
      'latitude': False
      'ram_total_size': False
      'tracking_mode': False
      'on_cloud': False
      'pue': False
SCALARS:
      duration: 100
      emissions: 100000000
      emissions_rate: 100000000
      energy_consumed: 1000000
LOG_TRANSFORMATION:
      'duration': True
      'emissions': True
      'emissions_rate': True
      'energy_consumed': True
OPERATIONAL_MODE:
      verbosity: 1   
      log_transformation: True
      apply_scalars: True
CARBON_BALANCE:
      tree_co2kg_ratio_min: 21.77
      tree_co2kg_ratio_max: 31.50
      tree_co2kg_ratio_avg: 26.63
      trees_per_hectare_avg: 500
 